# Generated by Django 4.1.2 on 2022-10-09 18:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelink',
            name='link',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
